import React, { useState } from 'react';
import { BarChart3, PieChart, ImageOff, Sparkles, Layers } from 'lucide-react';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000';

export const ShapViewer: React.FC = () => {
  const [summaryError, setSummaryError] = useState(false);
  const [barError, setBarError] = useState(false);

  const summaryUrl = `${API_BASE_URL}/reports/shap_summary.png`;
  const barUrl = `${API_BASE_URL}/reports/shap_bar.png`;

  const allUnavailable = summaryError && barError;

  return (
    <div className="bg-slate-800/70 border border-slate-700/60 rounded-2xl p-6 sm:p-8 shadow-xl backdrop-blur-sm mt-8">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between mb-6 pb-4 border-b border-slate-700/60 gap-3">
        <div>
          <h3 className="text-lg font-semibold text-white flex items-center gap-2">
            <Layers className="w-5 h-5 text-cyan-400" />
            Important Features (SHAP Explainability)
          </h3>
          <p className="text-xs text-slate-400 mt-1">
            SHapley Additive exPlanations showing relative k-mer contributions to genomic variant prediction.
          </p>
        </div>

        <div className="flex items-center gap-1.5 text-xs text-cyan-400 font-medium bg-cyan-950/40 border border-cyan-800/40 px-3 py-1.5 rounded-full self-start sm:self-auto">
          <Sparkles className="w-3.5 h-3.5" />
          <span>Generated by GeneMindAI</span>
        </div>
      </div>

      {allUnavailable ? (
        <div className="bg-slate-900/60 border border-slate-800 rounded-xl p-8 text-center flex flex-col items-center justify-center my-4">
          <ImageOff className="w-10 h-10 text-slate-600 mb-3" />
          <p className="text-sm font-medium text-slate-400">
            No explainability plots available.
          </p>
          <p className="text-xs text-slate-600 mt-1">
            Ensure model explainability pipeline has run and reports are hosted.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* SHAP Summary Beeswarm Plot */}
          <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-4 flex flex-col">
            <div className="flex items-center gap-2 text-xs font-semibold text-slate-300 mb-3">
              <PieChart className="w-4 h-4 text-cyan-400" />
              SHAP Summary Plot
            </div>
            {summaryError ? (
              <div className="flex-1 min-h-[220px] bg-slate-950/60 rounded-lg flex flex-col items-center justify-center p-4">
                <ImageOff className="w-8 h-8 text-slate-600 mb-2" />
                <span className="text-xs text-slate-500">No summary plot available</span>
              </div>
            ) : (
              <div className="overflow-hidden rounded-lg border border-slate-800/80 bg-white/5 p-2">
                <img
                  src={summaryUrl}
                  alt="SHAP Summary Plot"
                  onError={() => setSummaryError(true)}
                  className="w-full h-auto object-contain rounded hover:scale-[1.02] transition-transform duration-300"
                />
              </div>
            )}
          </div>

          {/* SHAP Bar Chart Plot */}
          <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-4 flex flex-col">
            <div className="flex items-center gap-2 text-xs font-semibold text-slate-300 mb-3">
              <BarChart3 className="w-4 h-4 text-cyan-400" />
              SHAP Bar Chart
            </div>
            {barError ? (
              <div className="flex-1 min-h-[220px] bg-slate-950/60 rounded-lg flex flex-col items-center justify-center p-4">
                <ImageOff className="w-8 h-8 text-slate-600 mb-2" />
                <span className="text-xs text-slate-500">No bar plot available</span>
              </div>
            ) : (
              <div className="overflow-hidden rounded-lg border border-slate-800/80 bg-white/5 p-2">
                <img
                  src={barUrl}
                  alt="SHAP Bar Plot"
                  onError={() => setBarError(true)}
                  className="w-full h-auto object-contain rounded hover:scale-[1.02] transition-transform duration-300"
                />
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
